name: Hello GitHub Actions
on: [push]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo “Hello from ${COURSE}!”
      - run: echo “I’ll list files.”
      - run: ls –al
  goodbye:
    needs: greet
    runs-on: ubuntu-latest
    steps:
      - run: echo “Goodbye from ${COURSE}!”
      - run: ls -al
